FROM nginx:stable-alpine3.17-slim

EXPOSE 80

WORKDIR /app
RUN mkdir ./build

RUN rm /etc/nginx/conf.d/default.conf
COPY ./react.conf /etc/nginx/conf.d

COPY ./build ./build

CMD ["nginx", "-g", "daemon off;"]