FROM node:lts-alpine3.18 as build

WORKDIR /app

COPY package.json . 
RUN npm install

COPY . .
RUN npm run build

############

FROM nginx:stable-alpine3.17-slim
COPY --from=build /app/build /usr/share/nginx/html